export interface VsTech {
  img?: string | null;
  icon?: string;
  color?: string;
  cat: string;
  level: number;
  desc: string;
  projects: string[];
  code: string;
}

/** Tech detail data for the VS Code stack window (ported from VS_TECH). */
export const VS_TECH: Record<string, VsTech> = {
  HTML5: { icon: 'ri-html5-fill', color: '#e34f26', cat: 'Frontend', level: 95, desc: '// Pondasi semua proyek web saya.\n// Semantik HTML5 untuk SEO & aksesibilitas optimal.', projects: ['Semua Proyek', 'Web Portfolio', 'Web Ecommerce'], code: '<!-- index.html -->\n<!DOCTYPE html>\n<html lang="id">\n<head>\n  <meta charset="UTF-8" />\n  <title>Damta Portfolio</title>\n</head>\n<body>\n  <div id="root"></div>\n</body>\n</html>' },
  CSS3: { icon: 'ri-css3-fill', color: '#264de4', cat: 'Frontend', level: 92, desc: '// Styling kompleks: Grid, Flexbox, Animasi.\n// Glassmorphism, Neon effects, dan desain responsif.', projects: ['Semua Proyek', 'Web Portfolio'], code: '/* Modern CSS - Grid + Custom Properties */\n:root {\n  --primary: #1d4ed8;\n  --radius: 1rem;\n}\n\n.hero {\n  display: grid;\n  grid-template-columns: 1fr 1fr;\n  gap: 2rem;\n  min-height: 100vh;\n}' },
  JavaScript: { icon: 'ri-javascript-fill', color: '#f7df1e', cat: 'Frontend', level: 88, desc: '// Logika interaktif sisi klien.\n// DOM manipulation, async/await, dan Fetch API.', projects: ['Semua Proyek', 'Web Relationship'], code: 'const fetchData = async (url) => {\n  const res = await fetch(url);\n  const data = await res.json();\n  return data;\n};\n\nfetchData("/api/projects");' },
  Go: { img: 'assets/img/go.png', cat: 'Backend (Go)', level: 72, desc: '// Compiled, statically-typed, lightning-fast.\n// High-performance API & microservices.', projects: ['API Service', 'Microservices'], code: 'package main\n\nimport "net/http"\n\nfunc main() {\n\thttp.HandleFunc("/api", handler)\n\thttp.ListenAndServe(":8080", nil)\n}' },
  Python: { img: 'assets/img/python.png', cat: 'AI / Scripting', level: 74, desc: '// Versatile: data science, scripting, automation.\n// AI pipeline dan data processing.', projects: ['AI Service', 'Automation'], code: 'from fastapi import FastAPI\napp = FastAPI()\n\n@app.get("/")\ndef root():\n    return {"hello": "world"}' },
  Rust: { img: 'assets/img/rust.png', cat: 'Systems (Rust)', level: 55, desc: '// Memory-safe, blazingly fast systems programming.\n// Zero-cost abstractions, no GC.', projects: ['CLI Tools', 'Systems'], code: 'fn main() {\n    let nums = vec![1, 2, 3];\n    let sum: i32 = nums.iter().sum();\n    println!("{}", sum);\n}' },
  Kotlin: { img: 'assets/img/kotlin.png', cat: 'Mobile (Android)', level: 63, desc: '// Modern JVM language for Android.\n// Concise, null-safe.', projects: ['Android App'], code: 'fun greet(name: String) = "Hello, $name!"\n\nfun main() {\n    println(greet("Damta"))\n}' },
  Java: { img: 'assets/img/java.png', cat: 'Backend (JVM)', level: 62, desc: '// Enterprise-grade OOP, JVM ecosystem.\n// Spring Boot, Android SDK.', projects: ['Enterprise Apps', 'Kampus'], code: 'public class Main {\n    public static void main(String[] args) {\n        System.out.println("Hello BKI");\n    }\n}' },
  Elixir: { img: 'assets/img/elixir.png', cat: 'Functional (Elixir)', level: 50, desc: '// Functional, fault-tolerant, Erlang VM.\n// Distributed & real-time apps.', projects: ['Learning'], code: 'defmodule Hello do\n  def world, do: IO.puts("Hello")\nend' },
  'C++': { img: 'assets/img/cpp.png', cat: 'Systems (C++)', level: 58, desc: '// High-performance systems & game dev.\n// RAII pattern.', projects: ['Algorithms'], code: '#include <iostream>\nint main() {\n  std::cout << "Hello";\n  return 0;\n}' },
  Ruby: { img: 'assets/img/ruby.png', cat: 'Scripting (Ruby)', level: 48, desc: '// Elegant scripting & Rails.\n// Convention over configuration.', projects: ['Automation'], code: 'puts "Hello from Ruby!"' },
  Lua: { img: 'assets/img/lua.png', cat: 'Scripting (Lua)', level: 45, desc: '// Lightweight embedded scripting.\n// Game modding & plugins.', projects: ['Game Scripting'], code: 'print("Hello from Lua")' },
  'React.js': { img: 'assets/img/react.png', cat: 'Frontend', level: 82, desc: '// Komponen reusable & state management.\n// Web portfolio & aplikasi dinamis.', projects: ['Web Portfolio', 'Web Rangkum Bisnis'], code: "import { useState } from 'react';\n\nfunction App() {\n  const [n, setN] = useState(0);\n  return <button onClick={() => setN(n+1)}>{n}</button>;\n}" },
  'Next.js': { img: 'assets/img/nextjs.png', cat: 'Frontend', level: 78, desc: '// SSR & SSG untuk performa tinggi.\n// Proyek full-stack modern.', projects: ['Web Rangkum Bisnis'], code: 'export default async function Page() {\n  const data = await fetch("/api/hello");\n  return <main>{await data.json()}</main>;\n}' },
  TypeScript: { img: 'assets/img/typescript.png', cat: 'Frontend', level: 76, desc: '// Superset JavaScript dengan static typing.\n// Mencegah bug & meningkatkan DX.', projects: ['Web Rangkum Bisnis'], code: 'interface User {\n  id: number;\n  name: string;\n}\n\nconst getUser = async (id: number): Promise<User> =>\n  db.user.findUnique({ where: { id } });' },
  'Tailwind CSS': { img: 'assets/img/tailwind.png', cat: 'Frontend', level: 85, desc: '// Utility-first CSS framework.\n// Mempercepat development.', projects: ['Web Rangkum Bisnis'], code: '<div className="flex items-center gap-4\n  rounded-2xl bg-white/10 p-6">\n  <h2 className="text-2xl font-bold">Hello</h2>\n</div>' },
  Bootstrap: { img: 'assets/img/bootstrap.png', cat: 'Frontend', level: 80, desc: '// Framework CSS responsif siap pakai.\n// Prototyping dan admin panel.', projects: ['Web Absensi', 'Web Ecommerce'], code: '<div class="container">\n  <div class="row">\n    <div class="col-md-6">Card</div>\n  </div>\n</div>' },
  'Framer Motion': { icon: 'ri-pulse-line', color: '#e74c3c', cat: 'Frontend', level: 68, desc: '// Library animasi React yang powerful.\n// Gesture, drag, stagger.', projects: ['Web Premium'], code: "import { motion } from 'framer-motion';\n\n<motion.div animate={{ opacity: 1 }} />" },
  GSAP: { icon: 'ri-magic-line', color: '#88ce02', cat: 'Frontend', level: 72, desc: '// GreenSock Animation Platform.\n// Scroll animations & timeline.', projects: ['Web Portfolio'], code: "gsap.to('.hero', {\n  opacity: 1,\n  scrollTrigger: '.hero'\n});" },
  'Three.js': { icon: 'ri-box-3-line', color: '#049ef4', cat: 'Frontend', level: 55, desc: '// 3D graphics di browser.\n// Efek visual 3D interaktif.', projects: ['Web Portfolio'], code: 'const scene = new THREE.Scene();\nconst camera = new THREE.PerspectiveCamera();' },
  Vite: { icon: 'ri-flashlight-line', color: '#a855f7', cat: 'Frontend', level: 75, desc: '// Build tool modern super cepat.\n// HMR dan bundle optimal.', projects: ['Web Rangkum Bisnis'], code: "import { defineConfig } from 'vite';\nimport react from '@vitejs/plugin-react';\n\nexport default defineConfig({ plugins: [react()] });" },
  'Node.js': { img: 'assets/img/node.png', cat: 'Backend', level: 78, desc: '// Runtime JavaScript sisi server.\n// REST API bersama Express.js.', projects: ['Backend API'], code: "import http from 'http';\nhttp.createServer((req, res) => {\n  res.end('ok');\n}).listen(3000);" },
  PHP: { img: 'assets/img/php.png', cat: 'Backend', level: 85, desc: '// Server-side scripting.\n// Native PHP untuk proyek custom.', projects: ['Web Absensi', 'Web Ecommerce'], code: "<?php\n$pdo = new PDO(\"mysql:host=localhost;dbname=db\");\n$stmt = $pdo->query(\"SELECT * FROM users\");\necho json_encode($stmt->fetchAll());" },
  'Express.js': { icon: 'ri-server-line', color: '#888', cat: 'Backend', level: 72, desc: '// Minimalist web framework untuk Node.js.\n// Routing, middleware, REST API.', projects: ['Web Rangkum Bisnis'], code: "import express from 'express';\nconst app = express();\napp.get('/api', (req, res) => res.json({ ok: true }));\napp.listen(3000);" },
  Hono: { icon: 'ri-fire-line', color: '#e36002', cat: 'Backend', level: 65, desc: '// Ultra-fast web framework edge runtime.\n// Lebih ringan dari Express.', projects: ['API Projects'], code: "import { Hono } from 'hono';\nconst app = new Hono();\napp.get('/', (c) => c.json({ ok: true }));" },
  Firebase: { img: 'assets/img/firebase.png', cat: 'Backend/DB', level: 80, desc: '// Backend-as-a-Service dari Google.\n// Realtime DB, Auth Google OAuth.', projects: ['Web Portfolio', 'Ruang Obrolan'], code: "import { getFirestore, addDoc } from 'firebase/firestore';\nawait addDoc(collection(db, 'messages'), { text: 'Hi' });" },
  Midtrans: { icon: 'ri-bank-card-line', color: '#003d73', cat: 'Backend', level: 70, desc: '// Payment gateway Indonesia.\n// Transfer bank, QRIS, e-wallet.', projects: ['Web Premium'], code: "const snap = new MidtransClient.Snap({ serverKey });\nawait snap.createTransaction({ ... });" },
  Cloudinary: { icon: 'ri-cloud-line', color: '#3448c5', cat: 'Backend', level: 68, desc: '// Cloud image & video management.\n// Upload, transform, serve media.', projects: ['Web Premium'], code: "const result = await cloudinary.uploader.upload(file, {\n  folder: 'portfolio'\n});" },
  NextAuth: { icon: 'ri-shield-keyhole-line', color: '#9c5de9', cat: 'Backend', level: 65, desc: '// Authentication untuk Next.js.\n// Google OAuth, JWT session.', projects: ['Web Rangkum Bisnis'], code: "import NextAuth from 'next-auth';\nimport Google from 'next-auth/providers/google';\nexport const { auth } = NextAuth({ providers: [Google] });" },
  'C Language': { img: 'assets/img/c.png', cat: 'Backend', level: 65, desc: '// Bahasa pemrograman level rendah.\n// Dasar algoritma & memori.', projects: ['Tugas Kampus'], code: '#include <stdio.h>\nint main() {\n  printf("Hello\\n");\n  return 0;\n}' },
  MySQL: { img: 'assets/img/mysql.png', cat: 'Database', level: 87, desc: '// Relational database management system.\n// Query kompleks, normalisasi.', projects: ['Web Absensi', 'Web Ecommerce'], code: 'CREATE TABLE absensi (\n  id INT AUTO_INCREMENT PRIMARY KEY,\n  karyawan_id INT NOT NULL,\n  status ENUM("hadir","izin","sakit")\n);' },
  'Prisma ORM': { icon: 'ri-database-2-line', color: '#5a67d8', cat: 'Database', level: 70, desc: '// ORM modern untuk TypeScript/Node.js.\n// Type-safe query builder.', projects: ['Web Rangkum Bisnis'], code: 'model User {\n  id    Int    @id @default(autoincrement())\n  email String @unique\n}' },
  Supabase: { icon: 'ri-database-fill', color: '#3ecf8e', cat: 'Database', level: 65, desc: '// Open-source Firebase alternative.\n// PostgreSQL, realtime, storage.', projects: ['Web Premium'], code: "const { data } = await supabase\n  .from('products')\n  .select('*');" },
  MongoDB: { icon: 'ri-leaf-line', color: '#4db33d', cat: 'Database', level: 60, desc: '// NoSQL document database.\n// Data tidak terstruktur.', projects: ['Backend API'], code: "const userSchema = new mongoose.Schema({\n  name: String,\n  email: String\n});" },
  Redis: { icon: 'ri-speed-line', color: '#dc382d', cat: 'Database', level: 60, desc: '// In-memory data store.\n// Caching, session, rate limiting.', projects: ['Backend API'], code: "await redis.setex('user:123', 3600, JSON.stringify(data));" },
  GitHub: { img: 'assets/img/github.png', cat: 'DevOps', level: 88, desc: '// Version control dan kolaborasi kode.\n// PR review, GitHub Actions.', projects: ['Semua Proyek'], code: 'git checkout -b feature/new-ui\ngit commit -m "feat: new dashboard"\ngit push origin feature/new-ui' },
  cPanel: { img: 'assets/img/cpanel.png', cat: 'DevOps', level: 80, desc: '// Web hosting control panel.\n// Deploy, domain, SSL.', projects: ['Web Absensi'], code: 'certbot certonly --webroot -d damtaweb.com' },
  Docker: { icon: 'ri-ship-line', color: '#2496ed', cat: 'DevOps', level: 58, desc: '// Containerization environment.\n// Dockerfile & docker-compose.', projects: ['Backend API'], code: 'FROM node:20-alpine\nWORKDIR /app\nCOPY . .\nRUN npm ci\nCMD ["node", "dist/index.js"]' },
  'Google Search Console': { img: 'assets/img/google search console.png', cat: 'DevOps', level: 75, desc: '// SEO monitoring & indexing.\n// Memastikan web terindeks Google.', projects: ['damtaweb.com'], code: '<url>\n  <loc>https://damtaweb.com/</loc>\n  <priority>1.0</priority>\n</url>' },
  'Gemini AI': { img: 'assets/img/gemini.png', cat: 'AI Tools', level: 85, desc: '// AI assistant dari Google.\n// Debugging, code review, optimasi.', projects: ['Semua Proyek'], code: 'const model = genAI.getGenerativeModel({ model: "gemini-2.5-flash" });\nconst res = await model.generateContent("...");' },
  'VS Code': { img: 'assets/img/vscode.png', cat: 'Tools', level: 95, desc: '// IDE utama untuk semua pengembangan.\n// ESLint, Prettier, GitLens.', projects: ['Semua Proyek'], code: '{\n  "editor.formatOnSave": true,\n  "editor.tabSize": 2\n}' },
  Project: { icon: 'ri-file-text-line', color: '#94a3b8', cat: 'Config', level: 100, desc: '// File konfigurasi proyek.\n// package.json, README, .env.', projects: ['Semua Proyek'], code: '{\n  "name": "damta-portfolio",\n  "version": "3.0.0"\n}' },
};
